20250408

diff --git a/.scripts/extra/wallcoffee b/.scripts/extra/wallcoffee
--- a/.scripts/extra/wallcoffee
+++ b/.scripts/extra/wallcoffee
@@ -23,15 +23,21 @@ get_random_wallpaper() {
 }
 
 if [ -n "$1" ]; then
-    if [ ! -f "$1" ]; then
+    if [ "$1" = "random" ]; then
+        WALL=$(get_random_wallpaper)
+    elif [ "$1" = "delete" ]; then
+        notify-send --app-name=Wallpaper --expire-time=2000 --icon="$CURRENT_WALLPAPER" "Wallpaper" "$CURRENT_WALLPAPER deleted !" 
+	rm "$CURRENT_WALLPAPER"
+        WALL=$(get_random_wallpaper)
+    elif [ ! -f "$1" ]; then
         notify-send "Wallpaper file '$1' not found!"
 	exit 1
     else
 	WALL="$(realpath "$1")"
-	echo "$WALL"
     fi
+    echo "Chosen wall : $WALL"
 else
-    WALL="$(echo -e "#Random\n$(ls "$WALLPAPER_DIR")\n#Delete\n#Import from clipboard" | rofi -config ~/.config/rofi/wallpaper.rasi -dmenu -replace -p " ")"    
+    WALL="$(echo -e "#Random\n$(ls "$WALLPAPER_DIR")\n#Delete" | rofi -dmenu -replace -p " ")"    
     if [ -n "$WALL" ]; then
 	case "$WALL" in
         "#Random")
@@ -42,16 +48,6 @@ else
 	    rm "$CURRENT_WALLPAPER"
             WALL=$(get_random_wallpaper)
 	    ;;
-        "#Import from clipboard")
-	    CLIPBOARD_CONTENT=$(wl-paste)
-            if is_image "$CLIPBOARD_CONTENT"; then
-                WALL="$CLIPBOARD_CONTENT"
-            else
-                notify-send --app-name=Wallpaper --expire-time=1000 "Not a valid image"
-		echo "Not a valid image"
-		exit 1
-            fi
-            ;;
         *)
             WALL="$WALLPAPER_DIR/$WALL"
             ;;
@@ -63,18 +59,15 @@ else
     fi
 fi
 
-swww img "$WALL" --transition-type grow --transition-fps 60 --transition-duration 3 --transition-bezier 0.65,0,0.35,1 --transition-pos 0.794,0.972 --transition-step 1 &
-
-wal -q -n -i "$WALL" || notify-send "Couldn't apply theme"
+wal -q -n -i "$WALL" || notify-send "Couldn't apply theme" && swww img "$WALL" --transition-type grow --transition-fps 60 --transition-duration 1.2 --transition-bezier 0.65,0,0.35,1 --transition-pos 0.794,0.972 --transition-step 1
 
 {
-    walogram -s
-    pywalfox update
     hyprctl reload
+    bash ~/.config/waybar/scripts/reload-waybar.sh || echo "Failed to reload waybar"
+    walogram -s
+#    pywalfox update
     sed -i "1s|$wall = .*|$wall = $WALL|" "$HOME/.config/hypr/hyprlock.conf" || notify-send "hyprlock failed"
     notify-send --app-name=Wallpaper --expire-time=2000 --icon="$WALL" "Wallpaper" "New wallpaper applied!" 
-    bash ~/.config/mako/update-theme.sh || echo "Failed to update mako theme"
-    bash ~/.config/waybar/scripts/reload-waybar.sh || echo "Failed to reload waybar"
 } &
 
 wait
